### ISSUE TITLE
More than 10k followers, multiple "followers" files. 

### ISSUE THREAD

**Issue by slevec** [aviolaris/instaunfollowers#62]
Doesn't seem to work for me, perhaps because I have 28k followers. 

My zip file contains multiple followers files. 
followers_1.html
followers_2.html
followers_3.html 

<img width="588" alt="Screenshot 2023-10-27 221030" src="https://github.com/aviolaris/instaunfollowers/assets/145139586/372ebfa0-e78f-4e56-b367-efc9674f1a14">

**Comment by aviolaris** [comment]
Thank you for bringing this to my attention. I've reviewed the issue and it appears that what you mentioned was indeed the cause of the problem.

I've made the necessary modifications to the code (based on the details you provided, as I don't have access to an account with more than 10k followers), and it should now handle cases where a large number of followers are split into multiple chunks.

Feel free to test the [updated version](https://github.com/aviolaris/instaunfollowers/releases/tag/v1.11.14), and if you encounter any further issues or have additional feedback, don't hesitate to let me know. Your input is valuable for improving the application's functionality.
