### ISSUE TITLE
Error: It seems that the structure of this archive is invalid

### ISSUE THREAD

**Issue by voaii** [aviolaris/instaunfollowers#80]
I got the following error:

> It seems that the structure of this archive is invalid, which is likely due to periodic modifications made by Meta to Instagram's information file in order to prevent tools like the present one from operating. Please file an issue so that the problem can be addressed.

**Comment by aviolaris** [comment]
Hello, thank you for reaching out. Meta has indeed recently made significant changes to both the Account Center and the structure of the Instagram Information File. Despite these alterations though, the app still seems capable of detecting unfollowers, as evidenced by tests conducted on two different accounts.

With that said, could you please confirm whether you used `HTML` as the format and not `JSON`? Additionally, if you did use `HTML`, could you kindly provide me with a screenshot of the directory `/connections/followers_and_following/` within your archive?
